- name: 配置etcd
  raw: |
    kubeadm alpha phase etcd local --config /tmp/kubeadm-config-{{ansible_hostname}}.yaml
    export KUBECONFIG=/etc/kubernetes/admin.conf
    kubeadm alpha phase etcd local --config /tmp/kubeadm-config-{{ansible_hostname}}.yaml

    kubectl exec -n kube-system etcd-{{init_hostname}} -- etcdctl --ca-file /etc/kubernetes/pki/etcd/ca.crt --cert-file /etc/kubernetes/pki/etcd/peer.crt --key-file /etc/kubernetes/pki/etcd/peer.key --endpoints=https://{{init_ip}}:2379 member add {{ansible_hostname}} https://{{ansible_default_ipv4.address}}:2380
  args:
    executable: /bin/bash
  when: ansible_hostname != init_hostname
  tags:
    - config-etcd

- name: 设置节点为master
  shell: |
    kubeadm alpha phase kubeconfig all --config /tmp/kubeadm-config-{{ansible_hostname}}.yaml
    kubeadm alpha phase controlplane all --config /tmp/kubeadm-config-{{ansible_hostname}}.yaml
    kubeadm alpha phase kubelet config annotate-cri --config /tmp/kubeadm-config-{{ansible_hostname}}.yaml
    kubeadm alpha phase mark-master --config /tmp/kubeadm-config-{{ansible_hostname}}.yaml
  when: ansible_hostname != init_hostname
  args:
    executable: /bin/bash
  tags:
    - config-master

