- name: 安装keepalived (CentOS)
  yum:
    name: keepalived
    state: present
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"
  tags:
    - install-keepalived-centos
    - keepalived
    
- name: 安装keepalived (Ubuntu)
  apt:
    name: keepalived
    state: present
  when:
    - ansible_distribution == "Ubuntu"
  tags:
    - install-keepalived-ubuntu
    - keepalived

- name: 配置keepalived
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
  tags:
    - configurate-keepalived
    - keepalived

- name: 启动keeplaived
  systemd:
    name: keepalived
    state: started
    enabled: yes
  tags:
    - start-keepalived
    - keepalived
