- name: 升级系统软件包 (CentOS)
  yum:
    name: '*'
    state: latest
  tags:
    - update

- name: 安装必须的软件包 (CentOS)
  yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
      - yum-plugin-versionlock
      - bind-utils
  tags:
    - docker

- name: 添加Docker仓库 (CentOS)
  copy:
    src: docker-ce.repo
    dest: /etc/yum.repos.d/
  tags:
    - add-docker-repo-centos
    - docker

- name: 安装Docker-ce (CentOS)
  yum:
    name: docker-ce
    state: present
  tags:
    - install-docker-centos
    - docker

- name: 启动Docker守护进程
  systemd:
    name: docker
    state: started
    enabled: yes
  tags:
    - start-docker
    - docker

- name: 锁定Docker-ce版本 (CentOS)
  shell: "yum versionlock add docker-ce"
  args:
    warn: no
  tags:
    - lock-docker-centos
    - docker

