- name: install keepalived the load balancer for CentOS
  yum:
    name: keepalived
    state: present
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"
    
- name: install keepalived the load balancer for Ubuntu
  apt:
    name: keepalived
    state: present
  when:
    - ansible_distribution == "Ubuntu"

- name: configurate keepalived
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf

- name: start keeplaived
  systemd:
    name: keepalived
    state: started
    enabled: yes
