- name: 添加kubeadm仓库 (CentOS)
  copy:
    src: kubernetes.repo
    dest: /etc/yum.repos.d/
  tags:
    - add-kubeadm-repo-centos

- name: 导入yum key (CentOS)
  rpm_key:
    key: https://mirrors.aliyun.com/kubernetes/yum/doc/yum-key.gpg 
    state: present
  tags:
    - k8s

- name: 导入rpm key (CentOS)
  rpm_key:
    key: https://mirrors.aliyun.com/kubernetes/yum/doc/rpm-package-key.gpg
    state: present
  tags:
    - k8s

- name: 安装kubeadm kubectl kubelet (CentOS)
  yum:
    name:
      - kubeadm 
      - kubectl
      - kubelet
    state: present
  tags:
    - install-kubeadm-centos
    - k8s

- name: 锁定kubeadm kubectl kubelet版本 (CentOS)
  shell: "yum versionlock add kubeadm kubelet kubectl"
  args:
    warn: no
  tags:
    - k8s

- name: 启动kubelet
  systemd:
    name: kubelet
    state: started
    enabled: yes
  tags:
    - start-kubelet
    - k8s
