- name: 关闭交换分区
  shell: "swapoff -a"

- name:  禁用SeLinux
  shell: "setenforce 0"

- name: 禁用firewalld
  systemd:
    name: firewalld
    state: stopped
    enabled: no
  when:
    - ansible_distribution == "CentOS"

- name: 准备kubeadm配置脚本
  template:
    src: generate_kubeadm_config.sh.j2
    dest: /tmp/generate_kubeadm_config.sh
  delegate_to: localhost
  tags:
    - prepare-config-script

- name: 创建kubeadm集群配置文件
  shell: /bin/bash /tmp/generate_kubeadm_config.sh
  delegate_to: localhost
  tags:
    - create-config

- name: 执行kubeadm init命令
  shell: kubeadm init --config "{{ temp_dir }}"/kubeadm-config-$(hostname).yaml

- name: 创建kubeadm管理用户(没有密码)
  user:
    name: kubernetes
    state: present

- name: 创建kubeadm context配置文件夹
  file:
    path: /home/kubernetes/.kube/
    owner: kubernetes
    state: directory

- name: 保存kubeadm context配置文件
  copy:
    remote_src: true
    src: /etc/kubernetes/admin.conf
    dest: /home/kubernetes/.kube/config
    owner: kubernetes

- name: 创建网络资源
  shell: "kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml"
  become: yes
  become_method: sudo
  become_user: kubernetes

- name: 生成加入集群的命令(kubeadm join)
  shell: "kubeadm token create --print-join-command 2>/dev/null"
  register: result  

- name: running set fact
  set_fact:
    kubernetes_join_command: "{{ result }}"

- name: print fact
  debug: msg="{{ kubernetes_join_command.stdout }}"
  
  
