# tasks file for kubernetes
#
#
- name: 配置系统
  import_tasks: configurate-system.yml

- name: 安装Docker-ce (CentOS)
  import_tasks: install-centos-docker.yml
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"

- name: 安装kubeadm kubectl kubelet (CentOS)
  import_tasks: install-centos-k8s-tools.yml
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"

- name: 安装Docker-ce (Ubuntu)
  import_tasks: install-ubuntu-docker.yml
  when:
    - ansible_distribution == "Ubuntu"

- name: 安装kubeadm kubectl kubelet (Ubuntu)
  import_tasks: install-ubuntu-k8s-tools.yml
  when:
    - ansible_distribution == "Ubuntu"

- name: 拉取相关Docker镜像
  import_tasks: pull-k8s-images.yml

- name: 安装keepalived
  import_tasks: install-keepalived.yml

- name: 执行kubeadm init命令
  import_tasks: kubeadm-init.yml

- name: 添加master节点
  import_tasks: add-master.yml

- name: 添加node节点
  import_tasks: kubeadm-join.yml
